global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'chillflow-local'
    environment: 'development'

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Application metrics (our Python services)
  - job_name: 'chillflow-apps'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'trip-assembler:8000'
          - 'stream-processor:8000'
          - 'batch-processor:8000'
          - 'host.docker.internal:8000'  # Local metrics server
    scrape_interval: 15s
    scrape_timeout: 10s

  # Container metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Kafka metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    scrape_timeout: 10s
