repos:
  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100, --target-version=py312, --check, --diff]

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100, --check-only, --diff]

  # Essential file checks only
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Ensure files end with newline
      - id: end-of-file-fixer
      # Check for large files
      - id: check-added-large-files
        args: [--maxkb=1000]
      # Check for merge conflict markers
      - id: check-merge-conflict
      # Check for debugger statements
      - id: debug-statements
      # Check YAML syntax
      - id: check-yaml
      # Check JSON syntax
      - id: check-json
