auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  ring:
    kvstore:
      store: inmemory
  replication_factor: 1

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  ingestion_burst_size_mb: 16
  ingestion_rate_mb: 4
  max_cache_freshness_per_query: 10m
  max_query_parallelism: 32
  max_query_series: 10000
  max_entries_limit_per_query: 10000
  max_query_length: 721h
  max_query_lookback: 721h
  max_streams_per_user: 10000
  max_line_size: 256000
  allow_structured_metadata: false

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7 days

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: false

analytics:
  reporting_enabled: false
