name: Code Quality

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Cache uv dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install dependencies
      run: |
        uv sync --all-extras

    - name: Run pre-commit hooks
      run: |
        uv run pre-commit run --all-files

    - name: Check code formatting with Black
      run: |
        uv run black --check --diff .

    - name: Check import sorting with isort
      run: |
        uv run isort --check-only --diff .

    - name: Run linting with flake8
      run: |
        uv run flake8 .

    - name: Check Makefile syntax
      run: |
        make --dry-run help > /dev/null
        echo "Makefile syntax is valid"
